# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-15 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='publish_time',
            field=models.DateTimeField(verbose_name='出版时间'),
        ),
    ]
